version: '3.1'

services:

  app:

    image: 'openjdk:8'

    build:

      context: .

    container_name: app

    volumes:

      - /fitter-current.jar:/etc/app/fitter-current.jar

    ports:

       - 8081:8081

    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false

    depends_on:

      - db

  db:

    image: mysql/mysql-server:latest

    container_name: db

    environment:

      MYSQL_ROOT_PASSWORD: bestuser

      MYSQL_USER: bestuser

      MYSQL_PASSWORD: bestuser

    ports:

      - 3306:3306

    restart: always